name: Building and testing

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
      fail-fast: false

    runs-on: ${{matrix.os}}
    timeout-minutes: 30

    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Upload Artefacts
        uses: actions/upload-artifact@v3
        with:
          name: advent-calendar-${{matrix.os}}
          path: build
